name: CodeCov

on:
  push:
    branches:
      - main
      - trying
      - staging
    tags: '*'
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.10'

    - name: Test with coverage
      run: |
        julia --project -e 'using Pkg; Pkg.instantiate()'
        julia --project -e 'using Pkg; Pkg.test(coverage=true)'

    - name: Generate coverage file
      run: julia --project -e 'using Pkg; Pkg.add("Coverage");
                               using Coverage;
                               LCOV.writefile("coverage-lcov.info", Codecov.process_folder())'
      if: success()

    - name: Submit coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{secrets.CODECOV_TOKEN}}
      if: success()

